name: drift-report

on:
  schedule:
    - cron: "0 9 * * 1"     # Mondays 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate drift report
        run: python monitor/generate_drift_report.py

      - name: Commit report if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh Evidently drift report"
          file_pattern: docs/drift_report.*
