name: drift-report

on:
  schedule:
    - cron: "0 5 * * 1"  # Mondays 05:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-drift-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Evidently report
        run: |
          python drift_monitor/build_report.py
      - name: Commit report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "Update drift report"
          git push
